# This is extended on the template provided in https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
name: CI actions

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: 
    - main
    - dev

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      shell: bash
      working-directory: cd digital-deck-server 
    - run: npm ci
      shell: bash
      working-directory: cd digital-deck-ui 
    - run: npm run test --if-present
      shell: bash
      working-directory: cd digital-deck-server 
    - run: npm run test --if-present
      shell: bash
      working-directory: cd digital-deck-ui 
    - run: node index.js
      shell: bash
      working-directory: cd digital-deck-server 
    - run: npm run build --if-present
      shell: bash
      working-directory: cd digital-deck-ui 
